"""empty message

Revision ID: 0704a0e72821
Revises: b15b25022c6c
Create Date: 2024-05-29 14:20:21.335507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0704a0e72821'
down_revision = 'b15b25022c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings_table.id'], name=op.f('fk_notes_table_recording_id_recordings_table')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recordings_table', schema=None) as batch_op:
        batch_op.drop_column('mp3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordings_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mp3', sa.VARCHAR(), nullable=False))

    op.drop_table('notes_table')
    # ### end Alembic commands ###
