"""empty message

Revision ID: 13527d4db1bd
Revises: 60822c2b2881
Create Date: 2024-05-20 13:22:34.197687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13527d4db1bd'
down_revision = '60822c2b2881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comments_table_user_id_users_table'), 'users_table', ['user_id'], ['id'])
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_comments_table_user_id_users_table'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
