"""empty message

Revision ID: 60822c2b2881
Revises: 
Create Date: 2024-05-20 13:12:49.176263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60822c2b2881'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('recordings_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mp3', sa.String(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_recordings_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings_table.id'], name=op.f('fk_comments_table_recording_id_recordings_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments_table')
    op.drop_table('recordings_table')
    op.drop_table('users_table')
    # ### end Alembic commands ###
