"""empty message

Revision ID: 75b1d55eae84
Revises: 0704a0e72821
Create Date: 2024-05-30 00:22:48.431714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b1d55eae84'
down_revision = '0704a0e72821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordings_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_instrument', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordings_table', schema=None) as batch_op:
        batch_op.drop_column('selected_instrument')

    # ### end Alembic commands ###
